services:
  - type: web
    name: meal-planner
    env: python
    pythonVersion: 3.9.0
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools wheel
      pip install .
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true 