services:
  - type: web
    name: meal-planner
    env: python
    buildCommand: pip install .
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true 